vich_uploader:
    db_driver: orm

    mappings:
        gig_images:
            uri_prefix: '%app.path.gig_images%'
            upload_destination: '%kernel.project_dir%/public/images/gigs'
            directory_namer: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
