vich_uploader:
    db_driver: orm

    mappings:
        gigs:
            uri_prefix: '%app.path.gig_images%'
            upload_destination: '%kernel.project_dir%/public/images/gigs'
            directory_namer: gigs.directory_namer
        gigimages:
            uri_prefix: '%app.path.gig_images%'
            upload_destination: '%kernel.project_dir%/public/images/gigs'
            directory_namer: gigimages.directory_namer
