easy_admin:
    design:
        menu:
            - label: 'Gigs'
              icon: 'shopping-basket'
              children:
                  - { entity: 'Category', icon: 'th-list', label: 'category' }
                  - { entity: 'Gigs', icon: 'th-list', label: 'gigs'  }
                  - { entity: 'GigImages', icon: 'th-list', label: 'gig image' }
            - { label: 'Utilisateur', entity: 'User', icon: 'users' }
