easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            label: 'Categories'
            list:
                title: 'Category'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - 'gigs'
            show:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label', css_class: 'large' }
                    - 'gigs'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'name', label: 'Label', css_class: 'large', help: 'Name of cateory' }
                    - { property: 'description', type:  'ckeditor',css_class: 'large'   }
                    # if you want to add products when creating categories, add the 'by_reference' option
                    # - { property: 'products', type_options: { by_reference: false } }
